import type { Address } from "viem";
import local from "../../contracts/deployments/local.json";
import { mosaicVaultAbi } from "./abi/MosaicVault";
import { usdgAbi } from "./abi/MockUSDG";
import { poolAdapterAbi } from "./abi/MockPoolAdapter";
import { lendingPoolAbi } from "./abi/MockLendingPool";

export { mosaicVaultAbi, usdgAbi, poolAdapterAbi, lendingPoolAbi };

export type PoolInfo = {
  name: string;
  pool: Address;
  adapter: Address;
  targetWeightBps: number;
  apyBps: number;
};

export type Deployment = {
  chainId: number;
  /** Block the vault was deployed at, so log scans have a real floor. */
  block?: number;
  deployer: Address;
  usdg: Address;
  vault: Address;
  pools: PoolInfo[];
};

/**
 * Production deployment, read from NEXT_PUBLIC_* at build time (see .env.example).
 * Literal `process.env.NEXT_PUBLIC_…` reads only — Next inlines nothing else.
 */
function productionDeployment(): Deployment | undefined {
  const chainId = Number(process.env.NEXT_PUBLIC_CHAIN_ID);
  const vault = process.env.NEXT_PUBLIC_VAULT_ADDRESS;
  const usdg = process.env.NEXT_PUBLIC_USDG_ADDRESS;
  if (!Number.isInteger(chainId) || chainId <= 0 || !vault || !usdg) return undefined;
  let pools: PoolInfo[] = [];
  try {
    const raw = process.env.NEXT_PUBLIC_POOLS;
    if (raw) pools = JSON.parse(raw) as PoolInfo[];
  } catch {
    pools = []; // a malformed list must not take the app down; adapters are read from chain anyway
  }
  const block = Number(process.env.NEXT_PUBLIC_DEPLOY_BLOCK);
  return {
    chainId,
    block: Number.isInteger(block) && block > 0 ? block : undefined,
    deployer: vault as Address,
    usdg: usdg as Address,
    vault: vault as Address,
    pools,
  };
}

/**
 * Single source of truth for contract addresses, keyed by chain id.
 * Local Anvil is generated by `npm run deploy:local` (contracts/deployments/local.json);
 * the production entry comes from the environment.
 */
const production = productionDeployment();

export const DEPLOYMENTS: Record<number, Deployment> = {
  [local.chainId]: local as Deployment,
  ...(production ? { [production.chainId]: production } : {}),
};

export const USDG_DECIMALS = 6;
/** Vault shares: 6 asset decimals + 6 ERC-4626 decimals offset. */
export const SHARE_DECIMALS = 12;
export const BPS = 10_000;

export function getDeployment(chainId?: number): Deployment | undefined {
  if (chainId === undefined) return undefined;
  return DEPLOYMENTS[chainId];
}
