// Copies contract ABIs from contracts/out into src/lib/abi as typed `as const` TS modules.
// Run after `forge build`: npm run abi:sync
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "contracts", "out");
const DEST = join(root, "src", "lib", "abi");
mkdirSync(DEST, { recursive: true });

const CONTRACTS = [
  ["MosaicVault.sol/MosaicVault.json", "mosaicVaultAbi", "MosaicVault.ts"],
  ["MockUSDG.sol/MockUSDG.json", "usdgAbi", "MockUSDG.ts"],
  ["MockPoolAdapter.sol/MockPoolAdapter.json", "poolAdapterAbi", "MockPoolAdapter.ts"],
  ["MockLendingPool.sol/MockLendingPool.json", "lendingPoolAbi", "MockLendingPool.ts"],
];

for (const [artifact, exportName, file] of CONTRACTS) {
  const { abi } = JSON.parse(readFileSync(join(OUT, artifact), "utf8"));
  const body = `// AUTO-GENERATED by scripts/sync-abi.mjs from contracts/out/${artifact}. Do not edit.\nexport const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(DEST, file), body);
  console.log(`wrote src/lib/abi/${file} (${abi.length} entries)`);
}
